version: '3.9'

services:
  app:
    build: .
    container_name: 'user-service'
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/marketplace?useUnicode=true&characterEncoding=UTF8"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "212109"
    depends_on:
      - mongodb
      - mysql-db
    restart: always


  mysql-db:
    image: mysql:8.0
    container_name: 'java_mysql'
    environment:
      MYSQL_DATABASE: marketplace
      MYSQL_ROOT_PASSWORD: "212109"
    restart: always
    volumes:
      - java_mysql:/var/lib/postgresql/data

  mongodb:
    image: 'mongo'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo/data
volumes:
  java_mysql:
  mongo: