databaseChangeLog:
  - changeSet:
      id: create-application
      author: Ilya Ignatovich
      changes:
        - createTable:
            tableName: application
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: first_name
                  type: varchar(255)
              - column:
                  name: last_name
                  type: varchar(255)
              - column:
                  name: message
                  type: varchar(1024)
              - column:
                  name: email
                  type: varchar(255)
                  constraints:
                    unique: true
                    nullable: false
              - column:
                  name: phone
                  type: varchar(255)
              - column:
                  name: role
                  type: varchar(255)